on:
  pull_request:
    types: [opened]
  push:
    branches:
      - main

jobs:
  linux:
    runs-on: docker
    image: meowlib-container
    steps:
      - uses: actions/checkout@v4
      - name: compile
        run: |
          mkdir build
          cd build
          cmake ..
          make -j$(nproc --all)
