on:
  pull_request:
    types: [opened]
  push:
    branches:
      - main

jobs:
  linux:
    runs-on: docker-linux
    container:
      image: meowlib-container
    steps:
      - uses: actions/checkout@v4
      - name: compile
        run: |
          mkdir build
          cd build
          cmake ..
          make -j$(nproc --all)
  windows:
    runs-on: host-windows
    steps:
      - uses: actions/checkout@v2
      - name: compile
        run: |
          & 'C:\Program Files\Microsoft Visual Studio\18\Community\Common7\Tools\Launch-VsDevShell.ps1' -Arch amd64
          mkdir build
          cd build
          cmake -G Ninja ..
          cmake --build . --config Release
