#include <cstdint>
#ifndef _INCLUDE_VOICE_VOICEOPCODES_H
#define _INCLUDE_VOICE_VOICEOPCODES_H
enum VoiceOpcodes : uint8_t {
  IDENTIFY,
  SELECT_PROTOCOL,
  READY,
  HEARTBEAT,
  SESSION_DESCRIPTION,
  SPEAKING,
  HEARTBEAT_ACK,
  CLIENT_CONNECT = 11,
  DAVE_PREPARE_TRANSITION = 21,
  DAVE_EXECUTE_TRANSITION = 22,
  DAVE_TRANSITION_READY = 23,
  DAVE_PREPARE_EPOCH = 24,
  DAVE_MLS_EXTERNAL_SENDER = 25,
  DAVE_MLS_KEY_PACKAGE = 26,
  DAVE_MLS_PROPOSALS = 27,
  DAVE_MLS_COMMIT_WELCOME = 28,
  DAVE_MLS_ANNOUNCE_COMMIT_TRANSITION = 29,
  DAVE_MLS_WELCOME = 30,
  DAVE_MLS_INVALID_COMMIT_WELCOME = 31,
};
#endif
